name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Login Dockerhub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      # - name: Build the Docker image
      #   run: docker build -t wa-watchapp .

      # - name: Tag the Docker image
      #   run: docker tag wa-watchapp:latest ranzeller/wa-watchapp:latest

      # - name: Push to Dockerhub
      #   run: docker push ranzeller/wa-watchapp:latest
