name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set OPENAI_API_KEY
        run: |
          OPENAI_API_KEY=$(aws ssm get-parameter --name /wa-bot/openAiApi --with-decryption --query Parameter.Value --output text)
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
      - name: run docker compose
        run: docker compose -f docker-compose.prod.yml up -d db
      - name: npm install
        run: npm install
      - name: run pm2
        run: npm run prod
